export const environment = {
  production: true,
  NEXT_PUBLIC_SUPABASE_URL: 'https://snbnywhixglgxstoqiyc.supabase.co',
  NEXT_PUBLIC_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuYm55d2hpeGdsZ3hzdG9xaXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MzU0ODIsImV4cCI6MjA3NTMxMTQ4Mn0.Mxd4G__QKUbsuj15Vrmaihuq2mnNG4YmX9fbW7Kj7lE',
  SUPABASE_SERVICE_ROLE_KEY:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuYm55d2hpeGdsZ3hzdG9xaXljIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTczNTQ4MiwiZXhwIjoyMDc1MzExNDgyfQ.t0JgM6OWnFgZt_wkD8U9l8JtiPc1suNPPUR-Yg_9dNA'
}
